services:
    _defaults:
        autowire:      true
        autoconfigure: true
    
    Customer\Controller\:
        resource: '../../src/Customer/Controller'
        tags: [ name: controller.service_arguments ]
