services:
    _defaults:
        autowire:      true
        autoconfigure: true
        
    Employee\Controller\:
        resource: '../../src/Employee/Controller'
        tags: [ name: controller.service_arguments ]
