
services:
    _defaults:
        autowire:      true
        autoconfigure: true
        
    ModuleA\Controller\:
        resource: '../../src/ModuleA/Controller'
        tags: [ name: controller.service_arguments ]
