
services:
    _defaults:
        autowire:      true
        autoconfigure: true
    
    ModuleB\Controller\:
        resource: '../../src/ModuleB/Controller'
        tags: [ name: controller.service_arguments ]
