services:
    _defaults:
        autowire:      true
        autoconfigure: true
        
    Employee\:
        resource: '../../src/Employee/'
        exclude: '../../src/Employee/Entity/'

    Employee\Command\:
        resource: '../../src/Employee/Command/'
        tags: [ 'console.command' ]
