services:
    _defaults:
        autowire:      true
        autoconfigure: true
        
    Rent\Controller\:
        resource: '../../src/Rent/Controller'
        tags: [ name: controller.service_arguments ]
