services:
    _defaults:
        autowire:      true
        autoconfigure: true
        
    Rental\Controller\:
        resource: '../../src/Rental/Controller'
        tags: [ name: controller.service_arguments ]
