doctrine:
    dbal:
        default_connection: customer_connection
        # multiple connections doctrine
        connections:
            customer_connection:
                url: '%env(resolve:DATABASE_URL_CUSTOMER)%'
            employee_connection:
                url: '%env(resolve:DATABASE_URL_EMPLOYEE)%'
            rental_connection:
                url: '%env(resolve:DATABASE_URL_RENTAL)%'
    orm:
        default_entity_manager: employee_em
        entity_managers:
            customer_em:
                connection: customer_connection
                mappings:
                    CCustomer:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Customer/Adapter/Database/ORM/Doctrine/Mapping'
                        prefix: 'Customer\Domain\Model'
                        alias: Customer\Domain\Model
            employee_em:
                connection: employee_connection
                mappings:
                    Employee:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/config/orm/mapping/employee'
                        prefix: 'Employee\Entity'
                        alias: Employee
            rental_em:
                connection: rental_connection
                mappings:
                    rental:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/config/orm/mapping/rental'
                        prefix: 'Rental\Entity'
                        alias: Rental

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
