customer:
    resource: '../src/Customer/Adapter/Framework/Config/Route/customer.yaml'
    prefix: 'customer'
    
employee:
    resource: 'routes/employee.yaml'
    prefix: 'employee'
    
rent:
    resource: 'routes/rent.yaml'
    prefix: 'rent'
